---
downloads: ~/.ansible-downloads/

dockutil_url: https://raw.githubusercontent.com/kcrawford/dockutil/master/scripts/dockutil
dockutil_install_path: /usr/local/bin/dockutil

# Catalina system applications are stored in /System/Applications/
# user added applications are stored in /Applications/
dockitems_to_persist:
  - name: Launchpad
    path: "/System/Applications/Launchpad.app"
    pos: 1
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 2
  - name: Royal TSX
    path: "/Applications/Royal TSX.app"
    pos: 3
  - name: iTerm 2
    path: "/Applications/iTerm.app"
    pos: 4
  - name: System Preferences
    path: "/System/Applications/System Preferences.app"
    pos: 5
  - name: Notes
    path: "/System/Applications/Notes.app"
    pos: 6