---
- name: Dockutil | Detect installation
  stat:
    path: "{{ dockutil_install_path }}"
  register: dockutil_stat

- name: Dockutil | Ensure installed.
  get_url:
    url: "{{ dockutil_url }}"
    dest: "{{ dockutil_install_path }}"
    mode: 0755
  when: not dockutil_stat.stat.exists

- name: Dockutil | Remove all dock items
  shell: "{{ dockutil_install_path }} --remove all --no-restart"
  register: removed_items_task

- name: Check if items in dock exist
  shell: dockutil --find '{{ item.name }}' || dockutil --add '{{ item.path }}'
  with_items: "{{ dockitems_to_persist }}"

- name: Fix order
  shell: dockutil --move '{{ item.name }}' --position {{ item.pos }}
  with_items: "{{ dockitems_to_persist }}"